name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libxcb-cursor0
    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
    - name: install
      run: ./install
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck
